# Generated by Django 4.0.3 on 2022-03-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TimeForm",
            new_name="TimeEntry",
        ),
    ]
