# Generated by Django 4.0.3 on 2022-03-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_rename_timeform_timeentry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timeentry",
            options={"verbose_name_plural": "Time Entries"},
        ),
        migrations.AddField(
            model_name="timeentry",
            name="hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
