# Generated by Django 4.0.3 on 2022-03-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_timeentry_options_timeentry_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="hours",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
    ]
