# Generated by Django 4.0.3 on 2022-03-10 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_timeentry_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
