# Generated by Django 4.0.3 on 2022-03-13 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="time_entry",
        ),
        migrations.AddField(
            model_name="timeentry",
            name="document",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.document",
            ),
        ),
    ]
