# Generated by Django 4.0.3 on 2022-03-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_remove_document_time_entry_timeentry_document"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Document",
            new_name="TimeSheet",
        ),
        migrations.RenameField(
            model_name="timeentry",
            old_name="document",
            new_name="timesheet",
        ),
    ]
