# Generated by Django 4.0.3 on 2022-03-14 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_note_timesheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="timesheet",
            field=models.ForeignKey(
                default="Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.timesheet",
            ),
        ),
    ]
