# Generated by Django 4.0.3 on 2022-03-16 16:05

from django.db import migrations, models
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_note_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('recurrences', recurrence.fields.RecurrenceField()),
            ],
        ),
    ]
