# Generated by Django 4.0.3 on 2022-03-16 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0014_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="timesheet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.timesheet",
            ),
        ),
    ]
